os: linux
language: node_js
node_js:
- 14
dist: focal
before_script:
- npm install -g travis-ci-cloudfront-invalidation
- npm install -g @angular/cli
script:
- ng lint
- ng build --prod
deploy:
  edge: true
  provider: s3
  local_dir: dist/ebird-maps-app
after_deploy:
- travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY_ID -s $AWS_SECRET_ACCESS_KEY -c $AWS_CLOUDFRONT_DIST_ID -i '/index.html' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST
